#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("PokemonApp.Resource", IsApplication=true)]

namespace PokemonApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Splat.Resource.String.library_name = global::PokemonApp.Resource.String.library_name;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050000
			public const int theme_custom_background = 2131034112;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int arrow = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int icon_pikachu = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int icon_pokedex = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int icon_superball = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int image_not_found = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int pokemon_arbok = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int pokemon_beedrill = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int pokemon_blastoise = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int pokemon_bulbasaur = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int pokemon_butterfree = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int pokemon_caterpie = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int pokemon_charizard = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int pokemon_charmander = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int pokemon_charmeleon = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int pokemon_ekans = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int pokemon_fearow = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int pokemon_ivysaur = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int pokemon_kakuna = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int pokemon_metapod = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int pokemon_pidgeot = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int pokemon_pidgeotto = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int pokemon_pidgey = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int pokemon_pikachu = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int pokemon_raticate = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int pokemon_rattata = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int pokemon_spearow = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int pokemon_squirtle = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int pokemon_venusaur = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int pokemon_wartortle = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int pokemon_weedle = 2130837533;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070022
			public const int arrow = 2131165218;
			
			// aapt resource value: 0x7f070027
			public const int create = 2131165223;
			
			// aapt resource value: 0x7f070001
			public const int gridview = 2131165185;
			
			// aapt resource value: 0x7f070004
			public const int login = 2131165188;
			
			// aapt resource value: 0x7f070003
			public const int password = 2131165187;
			
			// aapt resource value: 0x7f070028
			public const int pokemonIcon = 2131165224;
			
			// aapt resource value: 0x7f070029
			public const int pokemonName = 2131165225;
			
			// aapt resource value: 0x7f070017
			public const int pokemon_ability = 2131165207;
			
			// aapt resource value: 0x7f070016
			public const int pokemon_ability_label = 2131165206;
			
			// aapt resource value: 0x7f07000c
			public const int pokemon_attack = 2131165196;
			
			// aapt resource value: 0x7f07000b
			public const int pokemon_attack_label = 2131165195;
			
			// aapt resource value: 0x7f070019
			public const int pokemon_catch_rate = 2131165209;
			
			// aapt resource value: 0x7f070018
			public const int pokemon_catch_rate_label = 2131165208;
			
			// aapt resource value: 0x7f070010
			public const int pokemon_defense = 2131165200;
			
			// aapt resource value: 0x7f07000f
			public const int pokemon_defense_label = 2131165199;
			
			// aapt resource value: 0x7f070015
			public const int pokemon_egg_type = 2131165205;
			
			// aapt resource value: 0x7f070014
			public const int pokemon_egg_type_label = 2131165204;
			
			// aapt resource value: 0x7f070020
			public const int pokemon_evolution = 2131165216;
			
			// aapt resource value: 0x7f070021
			public const int pokemon_evolution_description = 2131165217;
			
			// aapt resource value: 0x7f070023
			public const int pokemon_evolution_image = 2131165219;
			
			// aapt resource value: 0x7f070024
			public const int pokemon_evolution_image_to = 2131165220;
			
			// aapt resource value: 0x7f07001f
			public const int pokemon_happiness = 2131165215;
			
			// aapt resource value: 0x7f07001e
			public const int pokemon_happiness_label = 2131165214;
			
			// aapt resource value: 0x7f07001b
			public const int pokemon_height = 2131165211;
			
			// aapt resource value: 0x7f07001a
			public const int pokemon_height_label = 2131165210;
			
			// aapt resource value: 0x7f07000a
			public const int pokemon_hp = 2131165194;
			
			// aapt resource value: 0x7f070009
			public const int pokemon_hp_label = 2131165193;
			
			// aapt resource value: 0x7f070007
			public const int pokemon_item_id = 2131165191;
			
			// aapt resource value: 0x7f070008
			public const int pokemon_item_image = 2131165192;
			
			// aapt resource value: 0x7f070006
			public const int pokemon_item_name = 2131165190;
			
			// aapt resource value: 0x7f070011
			public const int pokemon_profile = 2131165201;
			
			// aapt resource value: 0x7f07000e
			public const int pokemon_speed = 2131165198;
			
			// aapt resource value: 0x7f07000d
			public const int pokemon_speed_label = 2131165197;
			
			// aapt resource value: 0x7f070013
			public const int pokemon_type = 2131165203;
			
			// aapt resource value: 0x7f070012
			public const int pokemon_type_label = 2131165202;
			
			// aapt resource value: 0x7f07001d
			public const int pokemon_weight = 2131165213;
			
			// aapt resource value: 0x7f07001c
			public const int pokemon_weight_label = 2131165212;
			
			// aapt resource value: 0x7f070005
			public const int register = 2131165189;
			
			// aapt resource value: 0x7f070026
			public const int registerPassword = 2131165222;
			
			// aapt resource value: 0x7f070025
			public const int registerUsername = 2131165221;
			
			// aapt resource value: 0x7f070000
			public const int searchview = 2131165184;
			
			// aapt resource value: 0x7f070002
			public const int userName = 2131165186;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int GridViewLayout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int HomeScreenLayout = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int LoginLayout = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int PokemonDetailsLayout = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int RegisterLayout = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int ViewPokemonLayout = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040002
			public const int ApplicationName = 2130968578;
			
			// aapt resource value: 0x7f040006
			public const int CreateAccountFailedMessage = 2130968582;
			
			// aapt resource value: 0x7f040005
			public const int CreateAccountSuccessMessage = 2130968581;
			
			// aapt resource value: 0x7f040001
			public const int Hello = 2130968577;
			
			// aapt resource value: 0x7f040007
			public const int LoadingMessage = 2130968583;
			
			// aapt resource value: 0x7f040004
			public const int LoginFailedMessage = 2130968580;
			
			// aapt resource value: 0x7f040003
			public const int LoginSuccessMessage = 2130968579;
			
			// aapt resource value: 0x7f040000
			public const int library_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int Theme_Custom = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
